### PR TITLE
Design pass

### PR DESCRIPTION
**Pull request by wrightmartin**
A new homepage and various tweaks to layout, type and bootstrap components

screenshot-2018-1-29 mysociety data

### CODE REVIEW

**Comment by ajparsons** [comment]
I like the colourful logos!

Two (or three) things:

I turned off the off-grey background that's used in stuff like the research site behind the white because it did not play nicely with the javascript expanding the page for the search results. You may have already tried and similarly given up, but if poss it might be nice to get back in.

For the UK logo: could we try adding a few dots to do major cities? 

This would then be a me task to create, but do you think we want an explanatory blurb on homepage?

**Comment by wrightmartin** [comment]
> I turned off the off-grey background that's used in stuff like the research site behind the white because it did not play nicely with the javascript expanding the page for the search results. You may have already tried and similarly given up, but if poss it might be nice to get back in.

Yep, worth a go

> For the UK logo: could we try adding a few dots to do major cities?

Sure, let's see. If it doesn't work I can rethink it

> This would then be a me task to create, but do you think we want an explanatory blurb on homepage?

Yep, easy

**Comment by wrightmartin** [comment]
Hmm, the UK thing might have just swapped one too-abstract image for another

screen shot 2018-01-30 at 08 31 50

**Comment by ajparsons** [comment]
I always forget how far west Edinburgh is. I tried looking at all cities >200,000 but I'm still not sure it would jump out without the map:
image

image

I would suggest a flag, but that would ruin the colour thing. A monochrome flag?

**Comment by wrightmartin** [comment]
A bit more 'flaggy'?

screen shot 2018-01-30 at 10 00 06

**Comment by ajparsons** [comment]
Yep! One of the right is boring but fine!

**Comment by ajparsons** [comment]
Ok, I'll ask @MyfanwyNixon to help make this nicer but it's about the right length: can you give me a spot for it on the homepage?

```
mySociety services both produces a lot of useful (and interesting!) data. Over the years we’ve often made components or the results of mySociety services available through APIs or as open data to download (such as our EveryPolitician data).

This data portal brings all our published data together in one place to help people make the use of all the data products we provide.
```

**Comment by MyfanwyNixon** [comment]
Try this:

>From the [names and positions of the world's politicians](url), to [every speech made in Parliament since the 1930s](url): mySociety's many online projects generate a huge quantity of useful and interesting data, much of which can be accessed through APIs or as free-to-download Open Data. 

> This repository brings everything together in one place, so it's easy to see what's available, and to make use of it. Now dig in!

**Pull request merged**
